import { useEffect, useRef, useState } from "react";
import { Html5Qrcode } from "html5-qrcode";
import {
  QrCode,
  Camera,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  XCircle,
  Keyboard,
} from "lucide-react";
import api from "../../services/api";
import PageHeader from "../../components/PageHeader";
import { toast } from "../../utils/toast";

const SCANNER_ID = "qr-scanner-region";

function parsePayload(raw) {
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export default function ScanAttendance() {
  const scannerRef = useRef(null);
  const [scanning, setScanning] = useState(false);
  const [starting, setStarting] = useState(false);
  const [cameraError, setCameraError] = useState("");
  const [result, setResult] = useState(null); // success | error
  const [resultMsg, setResultMsg] = useState("");
  const [marking, setMarking] = useState(false);
  const [manualOpen, setManualOpen] = useState(false);
  const [sessionId, setSessionId] = useState("");
  const [token, setToken] = useState("");

  const stopScanner = async () => {
    if (scannerRef.current) {
      try {
        await scannerRef.current.stop();
      } catch {
        /* ignore */
      }
      scannerRef.current = null;
    }
  };

  const startScanner = async () => {
    setCameraError("");
    setResult(null);
    setStarting(true);
    try {
      const scanner = new Html5Qrcode(SCANNER_ID);
      scannerRef.current = scanner;
      await scanner.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 240, height: 240 } },
        async (decodedText) => {
          await stopScanner();
          setScanning(false);
          await handleDecoded(decodedText);
        },
        () => {}
      );
      setScanning(true);
    } catch (err) {
      setCameraError(
        "Camera permission was denied or no camera is available. Use manual entry instead."
      );
      toast("Camera permission failure — use manual entry", "error");
    } finally {
      setStarting(false);
    }
  };

  const handleDecoded = async (decodedText) => {
    const payload = parsePayload(decodedText);
    if (!payload || payload.t !== "attendance" || !payload.s || !payload.q) {
      setResult("error");
      setResultMsg("Invalid QR code. Please scan the attendance QR generated by your teacher.");
      toast("Invalid QR code", "error");
      return;
    }
    await markAttendance(payload.s, payload.q);
  };

  const markAttendance = async (sessionIdArg, tokenArg) => {
    setMarking(true);
    try {
      const res = await api.post("/attendance/mark", {
        sessionId: sessionIdArg,
        token: tokenArg,
      });
      setResult("success");
      setResultMsg(res.data.message || "Attendance Marked Successfully");
      toast("Attendance Marked Successfully");
    } catch (err) {
      setResult("error");
      const msg = err?.response?.data?.message || "Failed to mark attendance";
      setResultMsg(msg);
      toast(msg, "error");
    } finally {
      setMarking(false);
    }
  };

  const handleManual = async (e) => {
    e.preventDefault();
    if (!sessionId.trim() || !token.trim()) {
      toast("Session ID and token are required", "error");
      return;
    }
    await markAttendance(sessionId.trim(), token.trim());
  };

  useEffect(() => {
    return () => {
      stopScanner();
    };
  }, []);

  return (
    <div className="mx-auto max-w-xl">
      <PageHeader
        title="Scan Attendance"
        subtitle="Point your camera at the teacher's QR code."
        actions={
          <button onClick={() => setManualOpen((o) => !o)} className="btn-secondary">
            <Keyboard className="h-4 w-4" /> Manual Entry
          </button>
        }
      />

      {result ? (
        <div
          className={`card p-8 text-center ${
            result === "success" ? "border-emerald-300 dark:border-emerald-800" : "border-red-300 dark:border-red-800"
          }`}
        >
          {result === "success" ? (
            <CheckCircle2 className="mx-auto h-16 w-16 text-emerald-500" />
          ) : (
            <XCircle className="mx-auto h-16 w-16 text-red-500" />
          )}
          <h2 className={`mt-4 text-xl font-bold ${result === "success" ? "text-emerald-600 dark:text-emerald-400" : "text-red-600 dark:text-red-400"}`}>
            {result === "success" ? "✓ Attendance Marked Successfully" : "Attendance Failed"}
          </h2>
          <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{resultMsg}</p>
          <button
            onClick={() => {
              setResult(null);
              startScanner();
            }}
            className="btn-primary mt-6"
          >
            <Camera className="h-4 w-4" /> Scan another QR
          </button>
        </div>
      ) : (
        <>
          <div className="card p-6">
            {cameraError ? (
              <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-300">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                  <div>
                    <p className="font-semibold">Camera unavailable</p>
                    <p className="mt-1">{cameraError}</p>
                  </div>
                </div>
              </div>
            ) : null}

            <div className="overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700">
              {scanning ? (
                <div id={SCANNER_ID} className="w-full" />
              ) : (
                <div className="flex h-64 flex-col items-center justify-center gap-3 bg-slate-50 dark:bg-slate-950">
                  <QrCode className="h-12 w-12 text-slate-300" />
                  <p className="text-sm text-slate-400">Camera preview will appear here</p>
                </div>
              )}
            </div>

            <button
              onClick={scanning ? stopScanner : startScanner}
              disabled={starting || marking}
              className={`${scanning ? "btn-secondary" : "btn-primary"} mt-4 w-full`}
            >
              {marking ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" /> Marking attendance...
                </>
              ) : starting ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" /> Starting camera...
                </>
              ) : scanning ? (
                <>
                  <Camera className="h-4 w-4" /> Stop Camera
                </>
              ) : (
                <>
                  <Camera className="h-4 w-4" /> Start Camera
                </>
              )}
            </button>
          </div>

          {manualOpen ? (
            <div className="card mt-4 p-5">
              <h3 className="font-semibold">Manual Entry</h3>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                If you can't scan, enter the values from the QR payload shown on the teacher's screen.
              </p>
              <form onSubmit={handleManual} className="mt-3 space-y-3">
                <div>
                  <label className="label">Session ID</label>
                  <input className="input" value={sessionId} onChange={(e) => setSessionId(e.target.value)} placeholder="Paste session id from QR" />
                </div>
                <div>
                  <label className="label">Token</label>
                  <input className="input" value={token} onChange={(e) => setToken(e.target.value)} placeholder="Paste token from QR" />
                </div>
                <button type="submit" disabled={marking} className="btn-primary w-full">
                  {marking ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />} Mark Attendance
                </button>
              </form>
            </div>
          ) : null}
        </>
      )}
    </div>
  );
}
